### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by bonesoul** [the-pat/image-download#13]
I've been using the module for a while but getting an error when upgrading to 1.3.2:

```
11/1 11:59:01 [+629ms] - error: startup error: Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Coding\vizesizgezi.com\importer\node_modules\image-download\index.js from D:\Coding\vizesizgezi.com\importer\tasks\download\photo.js not supported.
Instead change the require of index.js in D:\Coding\vizesizgezi.com\importer\tasks\download\photo.js to a dynamic import() which is available in all CommonJS modules.
```

any ideas?

**Comment by the-pat** [comment]
@bonesoul, sorry for taking so long to respond!

Try adding this line to your `package.json`:
```
...
"type" : "module",
...
```

**Comment by bonesoul** [comment]
well not possible as my codebase still uses the old commonjs.

**Comment by the-pat** [comment]
Gotcha. That is my fault. I wanted to add `import`/`export` to the project. I didn't realize by adding `type: module` it would no longer be compatible with commonjs packages. I should have done a major version change.

If you'd still like to use this package, using  [`v1.3.0`](https://github.com/the-pat/image-download/tree/v1.3.0) should work. Or you could copy/paste the functionality from `index.js` into your code base (~10 lines of code).

I'm more than happy to accept a PR addressing this issue or I can address it in the near future.

**Comment by the-pat** [comment]
@bonesoul, I've updated the package to be compatible with CommonJS packages.

You should be able to use https://github.com/the-pat/image-download/releases/tag/v2.0.0. Thanks for pointing this out!

**Comment by bonesoul** [comment]
thanks i'll check it and write back here.

**Comment by bonesoul** [comment]
checked 2.1.0, everything is fine now. thanks!

**Comment by the-pat** [comment]
No problem! Thanks for checking out the changes!
